DROP TABLE IF EXISTS feedback;

CREATE TABLE feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) NOT NULL,
  category VARCHAR(250) DEFAULT NULL,
  text VARCHAR(250) DEFAULT NULL
);

